version: "3"

env:
  D: "stage prod"

tasks:
  make:
    desc: "Сделать всю инфру с нуля"
    cmds:
      - task: yc_prepare
      - task: packer_build
      - task: terraform_make
      - task: ansible_make
      - task: get_link

  terraform_make:
    desc: "Создание Terraform"
    cmds:
      - task: terraform_preinit
      - task: terraform_apply

  yc_prepare:
    desc: "Подготовка сетей, сервисного аккаунта и бакета"
    cmds:
      # - sh ./vm-make-config.sh
      - |
        fish -c 'source my-yc-command.fish && \
        yc_vpc_network_create && \
        yc_vpc_subnet_create && \
        yc_get_variables && \
        set -l D stage prod && \
        for d in $D; yc_vpc_subnet_create "app-subnet-$d"; end && \
        yc_backet_create_for_tfstate && \
        for svc in packerbuilder terraform
          yc_create_svc_acc $svc
        end && \
        echo Done'
  packer_build:
    desc: "Запекание образов Packer"
    cmds:
      - |
        fish -c 'source my-yc-command.fish && \
        yc_get_variables && \
        set -l p "-var-file=packer/variables.json -var subnet_id=$YC_SUBNET_ID" && \
        for f in packer/{app,db}.json
          for c in validate build
            set -l F true
            while $F
              echo Запуск Packer $c c $p для файла шаблона $f
              eval packer $c $p $f
              if test $status -eq 0
                set F false
              end
            end
          end
        end
        echo Done'

  terraform_preinit:
    desc: "Преинициализация Terraform"
    dir: terraform
    cmds:
      - |
        fish -c 'cp -av terraformrc.txt ~/.terraformrc && \
        set -l yc_tf yc_terraform.tf && \
        for d in app db vpc; pushd modules/$d; ln -vsf ../../$yc_tf.txt $yc_tf; popd; end && \
        for d in $D; pushd $d; ln -vsf ../$yc_tf.txt $yc_tf; popd; end && \
        for d in $D; pushd $d; for f in backend.tf variables.tf; ln -f ../$f .; end; popd; end && \
        echo Done'
      - bash ./make-tfvars.sh
    shell: fish

  terraform_apply:
    desc: "Применение конфигурации Terraform"
    dir: terraform
    cmds:
      - |
        fish -c 'function do-terraform
          begin
          terraform get
          ./terraform_init.sh
          terraform init -upgrade
          terraform validate
          terraform refresh
          terraform show
          terraform plan && terraform apply -auto-approve
          end && return 0 || return 1
        end && \
        set -l do do-terraform && \
        for d in (string split " " $D); pushd $d; echo "$do -> $d"; eval $do; popd; end && \
        echo Done'
    shell: fish

  terraform_upsize:
    desc: "Up size VM"
    dir: terraform
    cmds:
      - |
        fish -c 'for d in (string split " " $D)
          pushd $d
          for f in ../modules/app/main.tf
            sed -i "s/core_fraction =.*/core_fraction = 100/" $f
            sed -i "s/cores *=.*/cores = 4/" $f
            sed -i "s/memory *=.*/memory = 4/" $f
            terraform fmt $f
          end
          terraform apply -auto-approve
          terraform refresh
          popd
        end
        echo Done'

  terraform_downsize:
    desc: "Down size VM"
    dir: terraform
    cmds:
      - |
        fish -c 'for d in (string split " " $D)
          pushd $d
          for f in ../modules/app/main.tf
            sed -i "s/core_fraction =.*/core_fraction = 5/" $f
            sed -i "s/cores *=.*/cores = 2/" $f
            sed -i "s/memory *=.*/memory = 0.5/" $f
            terraform fmt $f
          end
          terraform apply -auto-approve
          terraform refresh
          popd
        end
        echo Done'
  terraform-destroy:
    desc: "Удаление инфры Terraform"
    dir: terraform
    cmds:
      - |
        fish -c 'set -l do "terraform apply -auto-approve -destroy"  && \
        for d in (string split " " $D); pushd $d; echo "$do -> $d"; eval $do; popd; end && \
        echo Done'

  clean:
    desc: "Удаление ресурсов Terraform и очистка облака"
    cmds:
      - |
        fish -c 'source my-yc-command.fish && \
        yc_get_variables && \
        pushd terraform  &&  \
        set -l D stage prod && \
        set -l do "terraform apply -auto-approve -destroy" && \
        for d in . $D; pushd $d; echo "$do -> $d"; eval $do; popd; end && \
        popd && \
        set -x YC_CONFIRM_DELETE yes; yc_all_delete_confirm all; set -e YC_CONFIRM_DELETE && \
        fd -HI -e tfstate -e tfstate.backup -X rm -fv && \
        fd -HItd .terraform -X rm -rfv && \
        fd -HItf terraform_init.sh -X rm -fv && \
        echo Done'

  show:
    desc: "Просмотр всех ресурсов"
    cmds:
      - task: show-yc
      - task: terraform-show
      - task: terraform-output
  show-yc:
    desc: "Просмотр облачных ресурсов"
    cmds:
      - |
        fish -c 'source my-yc-command.fish  &&  \
        yc_list_all  &&  \
        echo Done'
  terraform-output:
    desc: "Вывод переменных Terraform"
    dir: terraform
    cmds:
      - |
        fish -c 'set -l do "terraform output" && \
        for d in (string split " " $D); pushd $d; echo "$do -> $d"; eval $do; popd; end && \
        echo Done'
  terraform-show:
    desc: "Вывод конфига ресурсов Terraform"
    dir: terraform
    cmds:
      - |
        fish -c 'set -l D stage prod && \
        set -l do "terraform show" && \
        for d in . $D; pushd $d; echo "$do -> $d"; eval $do; popd; end && \
        echo Done'

  install_prereq:
    desc: "Установка необходимых пакетов"
    cmds:
      - task: install_python
      - task: install_ansible
  install_python:
    desc: "установить/обновить Python"
    cmds:
      - |
        sudo apt update && \
        sudo apt install -y --no-install-recommends  --no-install-suggests python3 python3-pip pipx  &&  \
        apt list --upgradable 2>/dev/null | \
        awk -F\/ '$1~/python/ {print $1}' | \
        xargs sudo apt install -y --only-upgrade
      - pip3 install -r requirements.txt  --user --break-system-packages

  install_ansible:
    desc: "установить/обновить Ansible"
    cmds:
      - pipx ensurepath
      - pipx install --include-deps ansible
      - pipx install --include-deps ansible-lint
      - pipx inject --include-apps ansible argcomplete
      - pipx upgrade --include-injected ansible

  get_link:
    desc: "Получение ссылки на веб-приложение"
    cmds:
      - task terraform-output | grep app | cut -f2 -d\" | xargs -I% echo -e 'http://%:9292\nhttp://%:80\n'

  ansible_make:
    desc: "Применение всей конфигурации Ansible"
    dir: ansible
    cmds:
      - task: terraform_upsize
      - task: ansible-inventory
      - task: ansible-apply
      - task: terraform_downsize
      - task: ansible-inventory

  ansible-inventory:
    desc: "Получение инвентаря Ansible"
    dir: ansible
    cmds:
      - task terraform-output 2>/dev/null | python3 inventory_dir/hosts111.py
      - ansible-inventory -i inventory -y --list > environments/$D/inventory.yaml
      - sed -i "s|^inventory =.*|inventory = ./environments/$D/inventory.yaml|" ansible.cfg

  ansible-apply:
    desc: "Применение конфигурации Ansible нужного варианта"
    cmds:
      - task: ansible-apply4

  ansible-apply1:
    desc: "Применение конфигурации Ansible вариант №1"
    dir: ansible
    cmds:
      - ansible all -m ping
      - ansible app -m apt -a "name=git state=present" -b
      # - ansible-playbook clone.yml
      - ln -s reddit_app_one_play.yml reddit_app.yml
      - ansible-playbook reddit_app.yml --limit db --tags db-tag
      - ansible-playbook reddit_app.yml --limit app --tags app-tag
      - ansible-playbook bundler.yml
      - ansible-playbook reddit_app.yml --limit app --tags deploy-tag
      - unlink reddit_app.yml

  ansible-apply2:
    desc: "Применение конфигурации Ansible вариант №2"
    dir: ansible
    cmds:
      - ansible all -m ping
      - ln -s reddit_app_multiple_plays.yml reddit_app2.yml
      - ansible-playbook reddit_app2.yml --tags db-tag
      - ansible-playbook reddit_app2.yml --tags app-tag
      - ansible-playbook reddit_app2.yml --tags deploy-tag
      - unlink reddit_app2.yml

  ansible-apply3:
    desc: "Применение конфигурации Ansible вариант №3"
    dir: ansible
    cmds:
      - ansible all -m ping
      # - ansible-playbook site.yml --check
      - ansible-playbook site.yml

  ansible-apply4:
    desc: "Применение конфигурации Ansible вариант №4"
    dir: ansible
    cmds:
      - ansible-galaxy install -r environments/$D/requirements.yml
      - ansible-galaxy collection install community.general
      - |
        fish -c '
          set -l F true
          while $F
            echo ============================== TRYING $D ==================
            ansible all -m ping && ansible-playbook playbooks/site.yml
            if test $status -eq 0
              set F false
            end
          end
          echo Done'
