cloud_id                 = "${TF_CLOUD_ID}"
folder_id                = "${TF_FOLDER_ID}"
zone                     = "${TF_ZONE}"
image_id                 = "${TF_IMAGE_ID}"
public_key_path          = "${TF_PUBLIC_KEY_PATH}"
private_key_path         = "${TF_PRIVATE_KEY_PATH}"
subnet_id                = "${TF_SUBNET_ID}"
service_account_key_file = "${TF_SERVICE_ACCOUNT_KEY_FILE}"
