---
- name: Packer prepare db host
  hosts: all
  become: true
  tasks:
    - name: Add APT key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present
    - name: Add MongoDB repository
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse"
        state: present
    - name: apt update and install dependencies
      apt:
        update_cache: yes
        cache_valid_time: 3600
        clean: yes
        name:
          - apt-transport-https
          - mongodb-org
        state: present
    - name: Enable mongod service
      systemd:
        name: mongod
        enabled: yes
